### ISSUE TITLE
Trakt.tv 'Now watching' reporting bugs

### ISSUE THREAD

**Issue by sambartik** [jellyfin/jellyfin-plugin-trakt#125]
Hello, I am currently on the plugin version 16 and have found that there are a few bugs that cause the status of 'now watching' on trakt.tv to be incorrect/out of sync.

1. Media is still being tracked as being watched if I close the media player via the back arrow icon in the upper left corner WHILE the video is still playing. If the video is paused, and then I click on the back icon, it correctly stops the watching status on Trakt.tv.
2. The watching status on Trakt.tv gets out of sync if I change the player's time position. The watching status continues to track as if I have not changed the time at all.

PS: Nonetheless, big thanks to everyone that took part and put in hard work to make this new version happen!

**Comment by Shadowghost** [comment]
1. I never checked that case but I guess we either don't receive a stop event or I messed something up in he handling, will look into it nonetheless.
2. You can fix that by pausing and unpausing after skipping. We currently don't have an event for skipping we can hook onto to properly handle this case (it's being looked at on the server side).

**Comment by sambartik** [comment]
What a shame, seems like fixes that need to happen at jellyfin's side. 

I have no idea of the inner workings of jellyfin and this plugin, so I don't know whether it is a bug, but when watching a media through 3rd party client, the watching status is not started at all. Is it a bug?

**Comment by crobibero** [comment]
Likely not a bug, but how the client is handling watch status. If it doesn't notify the server of position the plugin can't update the state

**Comment by sambartik** [comment]
@crobibero I dug into logs and seems that the app is reporting the progress:

```
[2022-04-24 20:28:59.877 +00:00] [INF] [128] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Infuse" "7.3.10" playing "XXXX". Stopped at "625" ms
[2022-04-24 20:28:59.892 +00:00] [INF] [143] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop tracker found, processing stop : "C60AA9E4-DDE4-4D16-BE37-FCC93A2F2CAE-0efb0c1a0dcb4d4e8b0799cf92c9925e-8ee6100156de4f1daf4238e731791438"
[2022-04-24 20:28:59.892 +00:00] [INF] [143] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Stop Event : 04/24/2022 20:28:59
[2022-04-24 20:28:59.892 +00:00] [INF] [143] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Saving playback tracking activity in DB
[2022-04-24 20:28:59.895 +00:00] [INF] [143] Trakt.ServerMediator: Playback stopped
[2022-04-24 20:29:00.003 +00:00] [INF] [101] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "Samuel" has succeeded.
[2022-04-24 20:29:00.003 +00:00] [INF] [101] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user "Samuel": 1/0
[2022-04-24 20:29:00.004 +00:00] [INF] [101] Emby.Server.Implementations.Session.SessionManager: Reissuing access token: "404e989dc3ed413b80cf9794c2d6abd5"
[2022-04-24 20:29:00.699 +00:00] [ERR] [126] Trakt.Api.TraktApi: Exception handled in PostToTrakt
System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (Bad Gateway).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.PostToTrakt[T](String url, Object data, TraktUser traktUser, CancellationToken cancellationToken)
[2022-04-24 20:29:00.700 +00:00] [ERR] [126] Trakt.ServerMediator: Exception occurred while sending a playback status update to trakt.tv for user "Samuel".
System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (Bad Gateway).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.PostToTrakt[T](String url, Object data, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendEpisodeStatusUpdateAsync(Episode episode, MediaStatus status, TraktUser traktUser, Single progressPercent, Boolean useProviderIds)
   at Trakt.ServerMediator.KernelPlaybackStopped(Object sender, PlaybackStopEventArgs playbackStoppedEventArgs)
[2022-04-24 20:31:12.192 +00:00] [ERR] [31] Trakt.Api.TraktApi: Exception handled in PostToTrakt
System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (Bad Gateway).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.PostToTrakt[T](String url, Object data, TraktUser traktUser, CancellationToken cancellationToken)
[2022-04-24 20:31:12.193 +00:00] [ERR] [31] Trakt.ServerMediator: Exception occurred while sending a playback status update to trakt.tv for user "Roman".
System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (Bad Gateway).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.PostToTrakt[T](String url, Object data, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendEpisodeStatusUpdateAsync(Episode episode, MediaStatus status, TraktUser traktUser, Single progressPercent, Boolean useProviderIds)
   at Trakt.ServerMediator.KernelPlaybackProgress(Object sender, PlaybackProgressEventArgs playbackProgressEventArgs)
[2022-04-24 20:31:12.346 +00:00] [ERR] [31] Trakt.Api.TraktApi: Exception handled in PostToTrakt
System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (Bad Gateway).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.PostToTrakt[T](String url, Object data, TraktUser traktUser, CancellationToken cancellationToken)
[2022-04-24 20:31:12.347 +00:00] [ERR] [31] Trakt.ServerMediator: Exception occurred while sending a playback status update to trakt.tv for user "Roman".
System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (Bad Gateway).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.PostToTrakt[T](String url, Object data, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendEpisodeStatusUpdateAsync(Episode episode, MediaStatus status, TraktUser traktUser, Single progressPercent, Boolean useProviderIds)
   at Trakt.ServerMediator.KernelPlaybackProgress(Object sender, PlaybackProgressEventArgs playbackProgressEventArgs)
[2022-04-24 20:31:12.492 +00:00] [ERR] [31] Trakt.Api.TraktApi: Exception handled in PostToTrakt
System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (Bad Gateway).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.PostToTrakt[T](String url, Object data, TraktUser traktUser, CancellationToken cancellationToken)
[2022-04-24 20:31:12.493 +00:00] [ERR] [31] Trakt.ServerMediator: Exception occurred while sending a playback status update to trakt.tv for user "Roman".
System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (Bad Gateway).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.PostToTrakt[T](String url, Object data, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendEpisodeStatusUpdateAsync(Episode episode, MediaStatus status, TraktUser traktUser, Single progressPercent, Boolean useProviderIds)
   at Trakt.ServerMediator.KernelPlaybackProgress(Object sender, PlaybackProgressEventArgs playbackProgressEventArgs)
[2022-04-24 20:31:12.681 +00:00] [ERR] [31] Trakt.Api.TraktApi: Exception handled in PostToTrakt
System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (Bad Gateway).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.PostToTrakt[T](String url, Object data, TraktUser traktUser, CancellationToken cancellationToken)
```

**Comment by sambartik** [comment]
I dug into logs and seems that the app is reporting the progress:

```
[2022-04-24 20:28:59.877 +00:00] [INF] [128] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Infuse" "7.3.10" playing "XXXX". Stopped at "625" ms
[2022-04-24 20:28:59.892 +00:00] [INF] [143] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop tracker found, processing stop : "C60AA9E4-DDE4-4D16-BE37-FCC93A2F2CAE-0efb0c1a0dcb4d4e8b0799cf92c9925e-8ee6100156de4f1daf4238e731791438"
[2022-04-24 20:28:59.892 +00:00] [INF] [143] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Stop Event : 04/24/2022 20:28:59
[2022-04-24 20:28:59.892 +00:00] [INF] [143] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Saving playback tracking activity in DB
[2022-04-24 20:28:59.895 +00:00] [INF] [143] Trakt.ServerMediator: Playback stopped
[2022-04-24 20:29:00.003 +00:00] [INF] [101] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "Samuel" has succeeded.
[2022-04-24 20:29:00.003 +00:00] [INF] [101] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user "Samuel": 1/0
[2022-04-24 20:29:00.004 +00:00] [INF] [101] Emby.Server.Implementations.Session.SessionManager: Reissuing access token: "404e989dc3ed413b80cf9794c2d6abd5"
[2022-04-24 20:29:00.699 +00:00] [ERR] [126] Trakt.Api.TraktApi: Exception handled in PostToTrakt
System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (Bad Gateway).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.PostToTrakt[T](String url, Object data, TraktUser traktUser, CancellationToken cancellationToken)
[2022-04-24 20:29:00.700 +00:00] [ERR] [126] Trakt.ServerMediator: Exception occurred while sending a playback status update to trakt.tv for user "Samuel".
System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (Bad Gateway).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.PostToTrakt[T](String url, Object data, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendEpisodeStatusUpdateAsync(Episode episode, MediaStatus status, TraktUser traktUser, Single progressPercent, Boolean useProviderIds)
   at Trakt.ServerMediator.KernelPlaybackStopped(Object sender, PlaybackStopEventArgs playbackStoppedEventArgs)
[2022-04-24 20:31:12.192 +00:00] [ERR] [31] Trakt.Api.TraktApi: Exception handled in PostToTrakt
System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (Bad Gateway).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.PostToTrakt[T](String url, Object data, TraktUser traktUser, CancellationToken cancellationToken)
[2022-04-24 20:31:12.346 +00:00] [ERR] [31] Trakt.Api.TraktApi: Exception handled in PostToTrakt
System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (Bad Gateway).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.PostToTrakt[T](String url, Object data, TraktUser traktUser, CancellationToken cancellationToken)
[2022-04-24 20:31:12.492 +00:00] [ERR] [31] Trakt.Api.TraktApi: Exception handled in PostToTrakt
System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (Bad Gateway).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.PostToTrakt[T](String url, Object data, TraktUser traktUser, CancellationToken cancellationToken)
[2022-04-24 20:31:12.681 +00:00] [ERR] [31] Trakt.Api.TraktApi: Exception handled in PostToTrakt
System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (Bad Gateway).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.PostToTrakt[T](String url, Object data, TraktUser traktUser, CancellationToken cancellationToken)
```

**Comment by sambartik** [comment]
Seemed it was a one-time bug. I can't reproduce it anymore. The 3rd party client works. Sorry.

**Comment by Shadowghost** [comment]
Welcome to the shitty trakt.tv API quality of service...
Seems like it's down again... Nothing we can do on our side about this.

**Comment by sambartik** [comment]
> 1. Media is still being tracked as being watched if I close the media player via the back arrow icon in the upper left corner WHILE the video is still playing. If the video is paused, and then I click on the back icon, it correctly stops the watching status on Trakt.tv.

Huh, seems that this issue has resolved by itself as well. Seems that the API could have been the one to blame all along. @Shadowghost 

I will do more testing and report if I have found anything. The only thing that remained was the 2nd point, which is out of this plugin's hands. 

Should we close this issue for now?
