### ISSUE TITLE
Unable to "Authorize device"

### ISSUE THREAD

**Issue by fad6b5f049** [jellyfin/jellyfin-plugin-trakt#13]
### System:
_**Jellyfin 10.3.0**_ with version _**2.0**_ of the **_trakt plugin_** (deleted plugins folder before installing). Jellyfin is running inside the official **_docker container_** on **_debian_**.

### Error:
Error when trying to **_"Authorize device"_**.

```
Alert
An error occurred when trying to authorize device: 404 - Not Found
```

### Logs:
_(note: I've replaced the username with [USER] and the unique user-id with [USERID])_

```
[2019-04-20 08:05:11.970 +00:00] [WRN] HTTP Response 200 to "172.18.0.11". Time (slow): 0:00:00.5299204. "http://jellyfin:8096/emby/users/[USERID]/items?Recursive=True&IncludeItemTypes=Movie&Fields=ProviderIds,Overview&startIndex=0&limit=200&IsVirtualItem=False"
[2019-04-20 08:05:22.886 +00:00] [INF] Authentication request for "[USER]" "has succeeded".
[2019-04-20 08:05:22.887 +00:00] [INF] Creating new access token for user [USERID]
[2019-04-20 08:05:23.001 +00:00] [ERR] Could not find handler for "/embywebsocket"
[2019-04-20 08:05:24.903 +00:00] [ERR] Could not find handler for "/embywebsocket"
[2019-04-20 08:05:57.230 +00:00] [ERR] Could not find handler for "/embywebsocket"
[2019-04-20 08:05:59.229 +00:00] [ERR] Could not find handler for "/embywebsocket"
[2019-04-20 08:06:03.494 +00:00] [ERR] Could not find handler for "/emby/Trakt/Users/[USERID]/Authorize"
[2019-04-20 08:06:11.250 +00:00] [ERR] Could not find handler for "/emby/Trakt/Users/[USERID]/Authorize"

```

Further up in the logs, this error also pops up

```
[2019-04-20 08:01:56.287 +00:00] [ERR] Error creating "Trakt.Api.TraktUriService"
System.InvalidOperationException: Unable to resolve service for type 'Trakt.Api.TraktApi' while attempting to activate 'Trakt.Api.TraktUriService'.
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
```

**Comment by 98WuG** [comment]
Having the same issue. Previously authorized accounts still work - just can't authorize new ones.

**Comment by anthonylavado** [comment]
Ack - trying to see what we can do about it

**Comment by Rhizix** [comment]
Just wanted to say I have the same issue, running Jellyfin on Windows

**Comment by rushfly** [comment]
jellyfin 10.5.0 and Trakt 7.0.0.0 have same issue.
