### ISSUE TITLE
Sync Error for Movies

### ISSUE THREAD

**Issue by LubricantJam** [jellyfin/jellyfin-plugin-trakt#138]
I believe there is also an error for the other sync too. 

```[2022-05-06 17:58:24.852 +00:00] [ERR] [59] Trakt.Api.TraktApi: Tried to reauthenticate with Trakt, but no refreshToken was available
[2022-05-06 17:58:24.960 +00:00] [ERR] [44] Trakt.ScheduledTasks.SyncLibraryTask: Exception handled in SyncMovies
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.GetFromTrakt[T](String url, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, IProgress`1 progress, Double currentProgress, Double availablePercent, CancellationToken cancellationToken)
[2022-05-06 17:58:24.962 +00:00] [ERR] [44] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.GetFromTrakt[T](String url, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, IProgress`1 progress, Double currentProgress, Double availablePercent, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncUserLibrary(User user, TraktUser traktUser, IProgress`1 progress, Double currentProgress, Double percentPerUser, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2022-05-06 17:58:24.963 +00:00] [INF] [44] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Export library to trakt.tv" Failed after 20 minute(s) and 28 seconds```

**Comment by Shadowghost** [comment]
That's a trakt.tv server error. Nothing we can do if their servers don't work.
