### ISSUE TITLE
Sync library to trakt.tv failed >> error 423 (locked)

### ISSUE THREAD

**Issue by Al4ndil** [jellyfin/jellyfin-plugin-trakt#164]
Server:
Version: 10.8.4
Operating System: Debian (docker)
Architecture: X64

Plugin: 19.0.0.0

Log:
`
[2022-08-30 13:40:49.798 +02:00] [INF] [8] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Export library to trakt.tv"
[2022-08-30 13:40:50.281 +02:00] [ERR] [27] Trakt.ScheduledTasks.SyncLibraryTask: Exception handled in SyncMovies
System.Net.Http.HttpRequestException: Response status code does not indicate success: 423 (Locked).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.GetFromTrakt[T](String url, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, IProgress`1 progress, Double currentProgress, Double availablePercent, CancellationToken cancellationToken)
[2022-08-30 13:40:50.286 +02:00] [ERR] [27] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.Net.Http.HttpRequestException: Response status code does not indicate success: 423 (Locked).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.GetFromTrakt[T](String url, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, IProgress`1 progress, Double currentProgress, Double availablePercent, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncUserLibrary(User user, TraktUser traktUser, IProgress`1 progress, Double currentProgress, Double percentPerUser, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2022-08-30 13:40:50.286 +02:00] [INF] [27] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Export library to trakt.tv" Failed after 0 minute(s) and 0 seconds
`

**Comment by Shadowghost** [comment]
According to trakt docs: `423 - Locked User Account (have the user contact support)`

Seems like your user account got locked and nedes to be unlocked by support - nothing we can do about that.

**Comment by Al4ndil** [comment]
So you think i need to ask to Trakt Support ?

**Comment by crobibero** [comment]
Yes. This isnt a Jellyfin issue
