### ISSUE TITLE
Exceptions for Trakt.Helpers.LibraryManagerEventsHelper - ProcessQueuedMovieEvents

### ISSUE THREAD

**Issue by alexandrucatalinene** [jellyfin/jellyfin-plugin-trakt#166]
I see it in my logs all the time. I didn't notice any problems for it (although I didn't actually check trakt to be sure)
```
[ERR] Error in OnQueueTimerCallbackInternal
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Trakt.Helpers.LibraryManagerEventsHelper.<>c__DisplayClass9_0.<ProcessQueuedMovieEvents>b__1(Movie lev)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToHashSet[TSource](IEnumerable`1 source, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToHashSet[TSource](IEnumerable`1 source)
   at Trakt.Helpers.LibraryManagerEventsHelper.ProcessQueuedMovieEvents(IReadOnlyCollection`1 events, TraktUser traktUser, EventType eventType)
   at Trakt.Helpers.LibraryManagerEventsHelper.OnQueueTimerCallbackInternal()
   at Trakt.Helpers.LibraryManagerEventsHelper.OnQueueTimerCallback(Object state)
```

**Comment by alvitali** [comment]
I'm experiencing the same issue! So many instances in my logs it's making it difficult to filter for other stuff...
