### ISSUE TITLE
Exception - Response status code does not indicate success 403 Forbidden

### ISSUE THREAD

**Issue by hubertbanas** [jellyfin/jellyfin-plugin-trakt#178]
I noticed 'import watched states and playback progress' stopped working few days ago for me.

Jellyfin version: 10.8.5
OS: Linux (x64)
Trakt: 20.0.0.0

I would appreciate any suggestions.

```bash
[2022-10-19 04:26:31.926 -04:00] [INF] "IntervalTrigger" fired for task: "Import watched states and playback progress from trakt.tv"
[2022-10-19 04:26:31.927 -04:00] [INF] Queuing task "SyncFromTraktTask"
[2022-10-19 04:26:31.927 -04:00] [INF] Executing "Import watched states and playback progress from trakt.tv"
[2022-10-19 04:26:31.987 -04:00] [INF] "IntervalTrigger" fired for task: "Export library to trakt.tv"
[2022-10-19 04:26:31.987 -04:00] [INF] Queuing task "SyncLibraryTask"
[2022-10-19 04:26:31.987 -04:00] [INF] Executing "Export library to trakt.tv"
[2022-10-19 04:26:32.089 -04:00] [ERR] Exception handled
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.GetFromTrakt[T](String url, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncFromTraktTask.SyncTraktDataForUser(User user, Double currentProgress, IProgress`1 progress, Double percentPerUser, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncFromTraktTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
[2022-10-19 04:26:32.090 -04:00] [ERR] Error syncing trakt.tv data for user "redacted-username"
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.GetFromTrakt[T](String url, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncFromTraktTask.SyncTraktDataForUser(User user, Double currentProgress, IProgress`1 progress, Double percentPerUser, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncFromTraktTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
[2022-10-19 04:26:32.090 -04:00] [INF] "Import watched states and playback progress from trakt.tv" Completed after 0 minute(s) and 0 seconds
[2022-10-19 04:26:32.091 -04:00] [INF] ExecuteQueuedTasks
[2022-10-19 04:26:32.157 -04:00] [ERR] Exception handled in SyncMovies
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.GetFromTrakt[T](String url, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, IProgress`1 progress, Double currentProgress, Double availablePercent, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncUserLibrary(User user, TraktUser traktUser, IProgress`1 progress, Double currentProgress, Double percentPerUser, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2022-10-19 04:26:32.158 -04:00] [ERR] Error
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Trakt.Api.TraktApi.GetFromTrakt[T](String url, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, IProgress`1 progress, Double currentProgress, Double availablePercent, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncUserLibrary(User user, TraktUser traktUser, IProgress`1 progress, Double currentProgress, Double percentPerUser, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2022-10-19 04:26:32.159 -04:00] [INF] "Export library to trakt.tv" Failed after 0 minute(s) and 0 seconds
[2022-10-19 04:26:32.159 -04:00] [INF] ExecuteQueuedTasks
```

**Comment by crobibero** [comment]
Plugin is disabled due to https://github.com/jellyfin/jellyfin-plugin-trakt/issues/174
