### ISSUE TITLE
Cannot load the plugins with jellyfin 10.8.5-8  on Synology DSM 6.2.3

### ISSUE THREAD

**Issue by Foxlandy1983** [jellyfin/jellyfin-plugin-trakt#181]
as title say：
  to start the Jellyfin，it is not work，the detail log file as follow shown：
[18:02:22] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Error creating Trakt.Plugin
System.UnauthorizedAccessException: Access to the path '/volume1/@appstore/jellyfin/var/data/plugins/trakt_21.0.0.0/meta.json' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at Emby.Server.Implementations.Plugins.PluginManager.SaveManifest(PluginManifest manifest, String path)
   at Emby.Server.Implementations.Plugins.PluginManager.CreatePluginInstance(Type type)
[18:02:22] [FTL] [1] Main: Error while starting server.
System.UnauthorizedAccessException: Access to the path '/volume1/@appstore/jellyfin/var/data/plugins/trakt_21.0.0.0/meta.json' is denied.
 ---> System.IO.IOException: Permission denied

**Comment by Foxlandy1983** [comment]
Permission denied，Setting permissions has been resolved, Thanks. :)
