### ISSUE TITLE
'Export library to trakt.tv' Failed (again/still)

### ISSUE THREAD

**Issue by mikewesten** [jellyfin/jellyfin-plugin-trakt#186]
This was fixed and working fine until very recently. The cause might be related to the recent server update to v10.8.6.
I did the usual steps of re-installing the plugin, reauthorizes with trakt, and restarting the server. No luck.
Manually trying to perform this action from the 'Scheduled Tasks' section.
However, only the 'Import watched states...' action is working without failure.

Here's the log:
`[2022-10-31 01:30:39.047 -07:00] [INF] Executing "Export library to trakt.tv"
[2022-10-31 01:30:41.255 -07:00] [ERR] Error
System.ArgumentException: Requested value 'Data' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse[TEnum](ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TEnum& result)
   at System.Enum.TryParse[TEnum](String value, Boolean ignoreCase, Boolean throwOnFailure, TEnum& result)
   at Emby.Server.Implementations.Data.SqliteItemRepository.GetMediaStream(IReadOnlyList`1 reader)
   at Emby.Server.Implementations.Data.SqliteItemRepository.GetMediaStreams(MediaStreamQuery query)
   at Emby.Server.Implementations.Library.MediaSourceManager.GetMediaStreams(MediaStreamQuery query)
   at Trakt.Extensions.MetadataIsDifferent(TraktMovieCollected collectedMovie, Movie movie)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, IProgress`1 progress, Double currentProgress, Double availablePercent, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncUserLibrary(User user, TraktUser traktUser, IProgress`1 progress, Double currentProgress, Double percentPerUser, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2022-10-31 01:30:41.256 -07:00] [INF] "Export library to trakt.tv" Failed after 0 minute(s) and 2 seconds
[2022-10-31 01:30:41.270 -07:00] [INF] ExecuteQueuedTasks`

I have everything checked except for:
Option 2 - 'Skip watched import from trakt.tv'
Option 5 - 'During Scheduled Task, set trakt.tv items to unwatched if local item is unwatched'
Option 7 - 'Set trakt.tv item to unwatched when local item is changed to unwatched.'

**Comment by Shadowghost** [comment]
This is a server caused bug. Will be fixed in 10.8.7.
