### ISSUE TITLE
[Trakt v22.0.0.0] An error occurred when trying to authorize device: 500 - Internal Server Error

### ISSUE THREAD

**Issue by oinmjb** [jellyfin/jellyfin-plugin-trakt#198]
Hello, I have a problem with authenticating Trakt, every time I try to authenticate a popup show and it says:
"Alert
An error occurred when trying to authorize device: 500 - Internal Server Error"

This started after the hammering the API issue, since that time I couldn't authenticate Trakt, even though I have updated Jellyfin and the Trakt plugin to the latest versions.

I uninstalled Jellyfin completely and deleted every folder that has Jellyfin name on it, and that didn't fix it.

OS: Windows 10 (for both server and client)
Jellyfin version: 10.8.9
Trakt plugin version: 22.0.0.0

Logs:
```
[2023-01-30 20:29:07.741 +03:00] [INF] [1] Main: Jellyfin version: "10.8.9"
[2023-01-30 20:29:07.766 +03:00] [INF] [1] Main: Environment Variables: ["[DOTNET_CLI_TELEMETRY_OPTOUT, 1]", "[JELLYFIN_LOG_DIR, C:\ProgramData\Jellyfin\Server\log]"]
[2023-01-30 20:29:07.772 +03:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--datadir", "C:\ProgramData\Jellyfin\Server"]
[2023-01-30 20:29:07.775 +03:00] [INF] [1] Main: Operating system: "Windows"
[2023-01-30 20:29:07.776 +03:00] [INF] [1] Main: Architecture: X64
[2023-01-30 20:29:07.778 +03:00] [INF] [1] Main: 64-Bit Process: True
[2023-01-30 20:29:07.780 +03:00] [INF] [1] Main: User Interactive: True
[2023-01-30 20:29:07.782 +03:00] [INF] [1] Main: Processor count: 8
[2023-01-30 20:29:07.783 +03:00] [INF] [1] Main: Program data path: "C:\ProgramData\Jellyfin\Server"
[2023-01-30 20:29:07.784 +03:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2023-01-30 20:29:07.786 +03:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2023-01-30 20:29:07.925 +03:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "C:\ProgramData\Jellyfin\Server\cache"
[2023-01-30 20:29:07.971 +03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2023-01-30 20:29:07.988 +03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Trakt, Version=22.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Trakt_22.0.0.0\Trakt.dll"
[2023-01-30 20:29:08.210 +03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2023-01-30 20:29:08.212 +03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2023-01-30 20:29:08.214 +03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2023-01-30 20:29:08.227 +03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2023-01-30 20:29:08.228 +03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2023-01-30 20:29:10.585 +03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Trakt" "22.0.0.0"
[2023-01-30 20:29:10.590 +03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.8.9.0"
[2023-01-30 20:29:10.592 +03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.8.9.0"
[2023-01-30 20:29:10.596 +03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.8.9.0"
[2023-01-30 20:29:10.598 +03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.8.9.0"
[2023-01-30 20:29:10.599 +03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.8.9.0"
[2023-01-30 20:29:10.661 +03:00] [INF] [1] Main: Kestrel listening on "Any IP4 Address"
[2023-01-30 20:29:11.069 +03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2023-01-30 20:29:11.127 +03:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 2023-01-31 02:00:00.000 +03:00, which is 05:30:48.8728939 from now.
[2023-01-30 20:29:11.242 +03:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "5.1.2"
[2023-01-30 20:29:11.332 +03:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "flac", "mp3"]
[2023-01-30 20:29:11.406 +03:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "libfdk_aac", "ac3", "flac", "libmp3lame", "libopus", "libvorbis", "srt"]
[2023-01-30 20:29:11.482 +03:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["deinterlace_qsv", "hwupload_cuda", "hwupload_vaapi", "overlay_opencl", "overlay_qsv", "overlay_cuda", "scale_cuda", "scale_opencl", "scale_qsv", "tonemap_cuda", "tonemap_opencl", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
[2023-01-30 20:29:11.793 +03:00] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: "overlay_vaapi" with option "Action to take when encountering EOF from secondary input" is not available
[2023-01-30 20:29:11.864 +03:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "dxva2", "qsv", "d3d11va", "opencl"]
[2023-01-30 20:29:12.057 +03:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: "ffmpeg"
[2023-01-30 20:29:12.061 +03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: "278918dfa1484d658c77ab982e42b8c8"
[2023-01-30 20:29:12.171 +03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.1012841
[2023-01-30 20:29:12.174 +03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[2023-01-30 20:29:12.396 +03:00] [INF] [12] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "E:\0 Movies\1080p\0 Unwatched Movies"
[2023-01-30 20:29:12.396 +03:00] [INF] [13] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "E:\0 Movies\1080p\0 Watched"
[2023-01-30 20:29:12.396 +03:00] [INF] [9] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "E:\0 Shows"
[2023-01-30 20:29:12.396 +03:00] [INF] [10] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "E:\Others"
[2023-01-30 20:29:12.407 +03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.2319709
[2023-01-30 20:29:12.410 +03:00] [INF] [1] Main: Startup complete 0:00:04.8289031
[2023-01-30 20:29:14.147 +03:00] [INF] [23] Emby.Server.Implementations.ScheduledTasks.TaskManager: "StartupTrigger" fired for task: "Update Plugins"
[2023-01-30 20:29:14.152 +03:00] [INF] [23] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "PluginUpdateTask"
[2023-01-30 20:29:14.158 +03:00] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Update Plugins"
[2023-01-30 20:29:14.158 +03:00] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"AccessSchedule"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-01-30 20:29:14.163 +03:00] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"ActivityLog"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-01-30 20:29:14.166 +03:00] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"CustomItemDisplayPreferences"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-01-30 20:29:14.169 +03:00] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"DisplayPreferences"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-01-30 20:29:14.172 +03:00] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"HomeSection"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-01-30 20:29:14.175 +03:00] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"ImageInfo"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-01-30 20:29:14.177 +03:00] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"ItemDisplayPreferences"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-01-30 20:29:14.180 +03:00] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"Permission"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-01-30 20:29:14.182 +03:00] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"Preference"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-01-30 20:29:14.184 +03:00] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"ApiKey"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-01-30 20:29:14.186 +03:00] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"Device"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-01-30 20:29:14.187 +03:00] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"DeviceOptions"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-01-30 20:29:14.189 +03:00] [WRN] [13] Microsoft.EntityFrameworkCore.Model.Validation: The entity type '"User"' is configured to use schema '"jellyfin"', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[2023-01-30 20:29:14.469 +03:00] [WRN] [9] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://127.0.0.1:8096/Sessions/Capabilities/Full" to "127.0.0.1" in 0:00:00.5148117 with Status Code 204
[2023-01-30 20:29:14.525 +03:00] [WRN] [13] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://127.0.0.1:8096/DisplayPreferences/usersettings?userId=6833b1c3dd9b4592b6f6251c27f4b979&client=emby" to "127.0.0.1" in 0:00:00.5656887 with Status Code 200
[2023-01-30 20:29:14.602 +03:00] [INF] [23] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" request
[2023-01-30 20:29:19.733 +03:00] [INF] [9] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 5 seconds
[2023-01-30 20:29:19.744 +03:00] [INF] [9] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2023-01-30 20:29:20.684 +03:00] [INF] [9] Trakt.Api.TraktController: TraktDeviceAuthorization request received
[2023-01-30 20:29:26.750 +03:00] [ERR] [4] Trakt.Api.TraktApi: Exception handled in PostToTrakt
System.NullReferenceException: Object reference not set to an instance of an object.
   at Trakt.Api.TraktApi.PostToTrakt[T](String url, Object data, TraktUser traktUser, CancellationToken cancellationToken)
[2023-01-30 20:29:26.776 +03:00] [ERR] [4] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Trakt/Users/6833b1c3dd9b4592b6f6251c27f4b979/Authorize".
System.NullReferenceException: Object reference not set to an instance of an object.
   at Trakt.Api.TraktApi.PostToTrakt[T](String url, Object data, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.AuthorizeDevice(TraktUser traktUser)
   at Trakt.Api.TraktController.TraktDeviceAuthorization(Guid userGuid)
   at lambda_method964(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2023-01-30 20:29:26.803 +03:00] [WRN] [4] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://127.0.0.1:8096/Trakt/Users/6833b1c3dd9b4592b6f6251c27f4b979/Authorize" to "127.0.0.1" in 0:00:06.1277643 with Status Code 500
```

**Comment by peanball** [comment]
I have the same issue on jellyfin 10.8.9 plug-in version 23.

> Version: 10.8.9
>
> Operating System: Linux
>
> Architecture: X64

New setup on a Synology NAS.

```
[2023-03-13 07:35:54.995 +01:00] [INF] [23] Trakt.Api.TraktController: TraktDeviceAuthorization request received
[2023-03-13 07:35:55.062 +01:00] [ERR] [35] Trakt.Api.TraktApi: Exception handled in PostToTrakt
System.NullReferenceException: Object reference not set to an instance of an object.
   at Trakt.Api.TraktApi.PostToTrakt[T](String url, Object data, TraktUser traktUser, CancellationToken cancellationToken)
[2023-03-13 07:35:55.066 +01:00] [ERR] [35] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Trakt/Users/867038f6d71e4519b929bcd30e603962/Authorize".
System.NullReferenceException: Object reference not set to an instance of an object.
   at Trakt.Api.TraktApi.PostToTrakt[T](String url, Object data, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.AuthorizeDevice(TraktUser traktUser)
   at Trakt.Api.TraktController.TraktDeviceAuthorization(Guid userGuid)
   at lambda_method1164(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```
