### ISSUE TITLE
authorize device 500 internal service error

### ISSUE THREAD

**Issue by yangtfu** [jellyfin/jellyfin-plugin-trakt#20]
## System:
Jellyfin 10.3.5 with version 4.0 of the trakt plugin. Jellyfin is running in windows server.
## Error:
An error occured when trying to authorize device:500 - Internal Server Error
## Log:
[Log.txt](https://github.com/jellyfin/jellyfin-plugin-trakt/files/3328045/Log.txt)

**Comment by Superpiffer** [comment]
I have the same problem, but a different error in log:
```
[2019-07-08 11:21:51.568 +02:00] [INF] DeviceAuthorization request received
[2019-07-08 11:21:51.569 +02:00] [ERR] Error processing request
System.MissingMethodException: Method not found: 'Void MediaBrowser.Common.Net.HttpRequestOptions.set_TimeoutMs(Int32)'.
   at Trakt.Api.TraktApi.GetHttpRequestOptions()
   at Trakt.Api.TraktApi.PostToTrakt(String url, Object data, CancellationToken cancellationToken, TraktUser traktUser)
```

**Comment by cvium** [comment]
Last bug is confirmed fixed by https://github.com/jellyfin/jellyfin/pull/1522
