### ISSUE TITLE
Plugin-Api connection seems to stop working after a few minutes

### ISSUE THREAD

**Issue by Torreip** [jellyfin/jellyfin-plugin-trakt#217]
Hello ! I recently reinstalled jellyfin and after revoking the trakt access. And reinstalling the plugin. I started to experience a weird behavior. The plugin works for 5 or 10 minutes. Before it stop being able to communicate with the api. After a bit of digging in the logs i find 3 messages :

```
[ERR] Exception handled in PostToTrakt
System.NullReferenceException: Object reference not set to an instance of an object.
   at Trakt.Api.TraktApi.PostToTrakt[T](String url, Object data, TraktUser traktUser, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendEpisodePlaystateUpdatesInternalAsync(IEnumerable`1 episodeChunk, TraktUser traktUser, Boolean seen, CancellationToken cancellationToken, Boolean useProviderIds)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
```

```
[2023-08-16 10:31:46.289 +00:00] [ERR] Exception handled in PostToTrakt
System.NullReferenceException: Object reference not set to an instance of an object.
   at Trakt.Api.TraktApi.PostToTrakt[T](String url, Object data, TraktUser traktUser, CancellationToken cancellationToken)
```

```
[2023-08-16 10:42:03.082 +00:00] [DBG] TraktSyncWatched { Movies: [TraktMovieWatched { WatchedAt: "2023-08-16T10:41:57.6270000Z", Title: "Summer Ghost", Year: 2021, Ids: TraktMovieId { Imdb: "tt15052770", Tmdb: 798544, Trakt: null, Slug: null } }], Shows: null, Episodes: null }
```

For me the last one means everything should have worked / has been executed but when i go check on the trakt website/app the thing I just watched dosen't appear.

The weird part however start. When i restart the server. (full reboot) it then work for 5-10min again before starting to not send anything to the trakt api.

What I have already tried :

Reinstalling The OS (Ubuntu 22.04 x68_64 QEMU inside of Proxmox VE)
Revoking the API access and reauthorize the device
Authorizing from Internet (through HAproxy) And Also Directly From the LAN
Unabling / Disabling Scrobbing (as it was way off and belived it could cause some issue)

Here are my settings for the plugin :
![pluggin Settings](https://github.com/jellyfin/jellyfin-plugin-trakt/assets/80983183/6fed8c61-573b-438d-beb3-30b6f84de4b0)

Could anyone Enlighten me on what I may be doing wrong / any solution or work around if this issue has already been encountred by anyone. (didn't find much similar to my issue but i might have missed it) 

Thank's in advance !
Torreip

**Comment by Torreip** [comment]
The issue disapeared for now. I don't know Why Or How (Maybe some Api Weirdness) but for now. I will close the issue
