### ISSUE TITLE
Cannot load plugin on Jellyfin 10.9.0

### ISSUE THREAD

**Issue by onigoetz** [jellyfin/jellyfin-plugin-trakt#229]
Hello,
I'm new to Jellyfin and I might have done something wrong.

Apparently this plugin is not compatible with the latest version of Jellyfin
Is this a known issue ?

```
[21:07:48] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly /config/plugins/Trakt_24.0.0.0/Trakt.dll. This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.TypeLoadException: Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
```

**Comment by crobibero** [comment]
plugins are not supported on unstable Jellyfin versions.
