### ISSUE TITLE
Does not sync anything on Jellyfin 10.5.0

### ISSUE THREAD

**Issue by Shadowghost** [jellyfin/jellyfin-plugin-trakt#33]
I upgraded to latest JF nightly in order to get proper hw accelleration and noticed that the trakt.tv import just writes to the log that it finished running after 0 seconds. Checking back in my library no watched states were synced at all.
```
[2020-01-16 08:46:54.993 +01:00] [INF] Executing "Import playstates from Trakt.tv"
[2020-01-16 08:46:55.030 +01:00] [INF] "Import playstates from Trakt.tv" Completed after 0 minute(s) and 0 seconds
[2020-01-16 08:46:55.031 +01:00] [INF] ExecuteQueuedTasks
```

If I can debug this further it would be nice if someone could tell me how. I already enabled the logging feature in the plugin but actually there isn't anything additional being logged.

**Comment by Shadowghost** [comment]
When trying to sync the library to trakt there is some more log output:
```
[2020-01-19 10:27:05.823 +01:00] [INF] Executing "Import playstates from Trakt.tv"
[2020-01-19 10:27:05.831 +01:00] [INF] "Import playstates from Trakt.tv" Completed after 0 minute(s) and 0 seconds
[2020-01-19 10:27:05.835 +01:00] [INF] ExecuteQueuedTasks
[2020-01-19 10:27:08.503 +01:00] [INF] Executing "Sync library to trakt.tv"
[2020-01-19 10:27:08.518 +01:00] [ERR] Error
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.InternalItemsQuery.set_OrderBy(System.ValueTuple`2<System.String,MediaBrowser.Model.Entities.SortOrder>[])'.
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncUserLibrary(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2020-01-19 10:27:08.539 +01:00] [INF] "Sync library to trakt.tv" Failed after 0 minute(s) and 0 seconds
```

In the webui this task is explicitly marked as failed while importing playstates isn't (but it doesn't work too).

**Comment by anthonylavado** [comment]
So it’s likely that a method in Jellyfin.Controller (MediaBrowser.controller) is no longer available, so the code here needs to be updated. Plugins are very hard to support with nightlies, because they depend on packages generated from the server, once it gets released.

**Comment by Shadowghost** [comment]
I didn't expect the plugins to work on the nightlies at all, but since it isn't I wanted to make sure that you know about it and can take care of it before a new stable server is released :)

**Comment by anthonylavado** [comment]
Thank you :-)

It’s a bit of a chicken and egg problem haha

**Comment by dannymichel** [comment]
Any plans on making it work for 10.5?
I moved on from 10.4 as my main

**Comment by bwaddington** [comment]
[05:30:28] [INF] [33] TaskManager: Executing Sync library to trakt.tv
[05:30:28] [ERR] [33] TaskManager: Error
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.InternalItemsQuery.set_OrderBy(System.ValueTuple`2<System.String,MediaBrowser.Model.Entities.SortOrder>[])'.
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncUserLibrary(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[05:30:28] [INF] [33] TaskManager: Sync library to trakt.tv Failed after 0 minute(s) and 0 seconds

**Comment by matthew-jones-uk** [comment]
10.5.0 has been [released](https://github.com/jellyfin/jellyfin/releases/tag/v10.5.0). 
Trakt is now broken on stable with the same error as above.

**Comment by dannymichel** [comment]
I was told that when 10.5 was released that all 10.4 plug-ins would be broken so you must upgrade to 10.5

**Comment by bwaddington** [comment]
i should of put on 

Server: Jellyfin
Version: 10.5.0
Operating System: Linux
Architecture: X64

**Comment by dkanada** [comment]
Plugin updates happen after the server releases, so there will be a delay before they receive new versions.

**Comment by matthew-jones-uk** [comment]
Removing [these](https://github.com/jellyfin/jellyfin-plugin-trakt/blob/3d79fac4f1d8b90460288fbe1b2f4522e069565c/Trakt/ScheduledTasks/SyncFromTraktTask.cs#L137) lines of code seem to fix the problem, however I had to use commit fb6ec5ea5ac55d3f69da6679b96f24450f9b693b as newer versions were giving me an HTTP error 500 once used.

**Comment by lldsolitude** [comment]
I'm reopening this because the latest code does not build:
```
Api/TraktApi.cs(121,68): error CS1503: Argument 1: cannot convert from 'System.Globalization.CultureInfo' to 'int'
Api/TraktApi.cs(174,72): error CS1503: Argument 1: cannot convert from 'System.Globalization.CultureInfo' to 'int'
Api/TraktApi.cs(195,76): error CS1503: Argument 1: cannot convert from 'System.Globalization.CultureInfo' to 'int'
```

**Comment by dkanada** [comment]
#39
