### ISSUE TITLE
An error occurred when trying to authorize device: 500 - Internal Server Error

### ISSUE THREAD

**Issue by asgarder** [jellyfin/jellyfin-plugin-trakt#41]
Getting an error "An error occurred when trying to authorize device: 500 - Internal Server Error" when trying to link Trakt account. 

Jellyfin on version 10.5.0

**Comment by Deanosim** [comment]
I'm also getting this error on a brand new fresh install of Jellyfin Nightly 10.6.0 that I installed to test 10.6.0.

The only error I can see in the log file is this:
```[2020-06-20 14:28:06.951 +10:00] [ERR] [35] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://192.168.1.200:8096/Trakt/Users/01182fb6a44048c5be86b7c1bff9f6ee/Authorize"
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Trakt.Api.TraktUriService'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstance(Type type)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.CreateInstance(Type type)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)```

**Comment by oddstr13** [comment]
Yes, that error log is due to running a plugin not yet updated for the generic ILogger removal in 10.6.

I did test the plugin for the 10.7 update, but please create a new issue if you are having trouble with linking in the upcoming Jellyfin 10.7 release.
