### ISSUE TITLE
Sync library to trakt.tv failed

### ISSUE THREAD

**Issue by MateEke** [jellyfin/jellyfin-plugin-trakt#45]
Server: 
Version: 10.5.5
Operating System: Linux
Architecture: X64

Plugin: 9.0.0.0

Log:
```
The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset') at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset) at System.DateTimeOffset..ctor(DateTime dateTime) at System.DateTimeOffset.op_Implicit(DateTime dateTime) at Trakt.Api.TraktApi.SetRequestHeaders(HttpRequestOptions options, TraktUser traktUser) at Trakt.Api.TraktApi.GetFromTrakt(String url, CancellationToken cancellationToken, TraktUser traktUser) at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser) at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken) at Trakt.ScheduledTasks.SyncLibraryTask.SyncUserLibrary(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken) at Trakt.ScheduledTasks.SyncLibraryTask.Execute(CancellationToken cancellationToken, IProgress`1 progress) at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
```

**Comment by Zusier** [comment]
I have the EXACT issue on windows. Have force re-authorized multiple times so I dont think thats the issue

**Comment by Zusier** [comment]
Welp, after running into a completely different issue with my library it works now :p

**Comment by oddstr13** [comment]
Is this issue still present in Jellyfin 10.6.3 with plugin version 9?

What is your system timezone?

**Comment by int3ro** [comment]
I have the same issue:

`[2020-11-06 00:10:33.474 +01:00] [INF] [32] Emby.Server.Implementations.ScheduledTasks.TaskManager: "IntervalTrigger" fired for task: "Sync library to trakt.tv"
[2020-11-06 00:10:33.475 +01:00] [INF] [32] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queueing task "SyncLibraryTask"
[2020-11-06 00:10:33.476 +01:00] [INF] [4] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Sync library to trakt.tv"
[2020-11-06 00:10:33.518 +01:00] [ERR] [4] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')
   at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
   at System.DateTimeOffset..ctor(DateTime dateTime)
   at System.DateTimeOffset.op_Implicit(DateTime dateTime)
   at Trakt.Api.TraktApi.SetRequestHeaders(HttpRequestOptions options, TraktUser traktUser)
   at Trakt.Api.TraktApi.GetFromTrakt(String url, CancellationToken cancellationToken, TraktUser traktUser)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncUserLibrary(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2020-11-06 00:10:33.554 +01:00] [INF] [4] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Sync library to trakt.tv" Failed after 0 minute(s) and 0 seconds`

Version: 10.6.4
Operating System: Linux
Architecture: X64
Plugin Version: 10.0.0.0

**Comment by jcaldeira** [comment]
Version: 10.6.4
Operating System: Windows
Architecture: X64
Plugin Version: 10.0.0.0

I don't think my type of logs error are the same, but I do have the same problem: "Sync library to trakt.tv failed"
I'll leave a link to my [logs](https://pastebin.com/CTuwJFz8). I did pick some log lines out that were in the middle of it this error in particular. I hope all information is in there.

**Comment by Shadowghost** [comment]
Anyone still expereincing this with the current plugin?

**Comment by crobibero** [comment]
Initial guess is that we need to guard for items with a parameter of DateTime.MinValue

**Comment by Shadowghost** [comment]
Indeed. But that should normally never happen...

**Comment by JRDevo** [comment]
Version 20.0.0.0 solved this for me, thanks!

**Comment by Shadowghost** [comment]
My guess is that the main problem was caused by old versions of the plugin not setting the expiration date of the access token properly. We now have a fallback which seems to fix this cases (reauthentication should have done the trick too).

Please reopen or create a new issue if this comes up after you removed the config file and reauthed your user.
