### ISSUE TITLE
Import playstates from Trakt.tv failed

### ISSUE THREAD

**Issue by ToXinE** [jellyfin/jellyfin-plugin-trakt#51]
Jellyfin 10.6.0 
Trakt.tv 9.0.0.0
with docker jellyfin/jellyfin
`[2020-07-21 16:27:10.736 +00:00] [INF] Executing "Import playstates from Trakt.tv"
[2020-07-21 16:27:10.772 +00:00] [ERR] Error
System.TypeLoadException: Could not load type 'MediaBrowser.Controller.Entities.User' from assembly 'MediaBrowser.Controller, Version=10.6.0.0, Culture=neutral, PublicKeyToken=null'.
   at Trakt.ScheduledTasks.SyncFromTraktTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2020-07-21 16:27:10.772 +00:00] [INF] "Import playstates from Trakt.tv" Failed after 0 minute(s) and 0 seconds`

**Comment by crobibero** [comment]
The latest trakt plugin is 10.0.0.0. Please update the plugin and try again.

**Comment by EVOTk** [comment]
Same problem.
After updating to 10.0.0.0, it works normally again! Thank you :D

**Comment by ToXinE** [comment]
upgrading seems to solve the problem thanks !
