### ISSUE TITLE
Sync with Trakt not play

### ISSUE THREAD

**Issue by EVOTk** [jellyfin/jellyfin-plugin-trakt#52]
Hello,
i'm updrading to Jellyfin 10.6.0 et Trakt 10.0.0.0
I thought it worked, but it doesn't! I regularly have errors

In log : 

Sync library to trakt.tv failed
Import playstates from Trakt.tv failed

`Could not load type 'MediaBrowser.Controller.Entities.User' from assembly 'MediaBrowser.Controller, Version=10.6.0.0, Culture=neutral, PublicKeyToken=null'. at Trakt.ScheduledTasks.SyncFromTraktTask.Execute(CancellationToken cancellationToken, IProgress`1 progress) at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)`

**Comment by crobibero** [comment]
Did you restart after updating the plugin?

**Comment by EVOTk** [comment]
Yes!

**Comment by crobibero** [comment]
I can't replicate this, and the function doesn't reference `MediaBrowser.Controller.Entities.User`

**Comment by oddstr13** [comment]
This looks like you where running the old version of the plugin (updated, but not restarted).

Do you still see this exact error message?

**Comment by EVOTk** [comment]
In docker logs : 

[13:26:51] [ERR] [31] Trakt.ScheduledTasks.SyncFromTraktTask: Error syncing trakt data for user Evoluzione
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at ServiceStack.StreamExtensions.CopyToNewMemoryStream(Stream stream) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\StreamExtensions.cs:line 508
   at ServiceStack.Memory.NetCoreMemory.Deserialize(Stream stream, Type type, DeserializeStringSpanDelegate deserializer) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\NetCoreMemory.cs:line 151
   at ServiceStack.Text.JsonSerializer.DeserializeFromStream[T](Stream stream) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\JsonSerializer.cs:line 190
   at Trakt.Api.TraktApi.SendGetWatchedShowsRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncFromTraktTask.SyncTraktDataForUser(User user, Double currentProgress, CancellationToken cancellationToken, IProgress`1 progress, Double percentPerUser)
   at Trakt.ScheduledTasks.SyncFromTraktTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)

**Comment by oddstr13** [comment]
Memory issues should have been improved in 10.6.1 and 10.6.2
