### ISSUE TITLE
Sync/Import not working on 10.6.2

### ISSUE THREAD

**Issue by 1024mb** [jellyfin/jellyfin-plugin-trakt#54]
I get this every time any of the two scheduled task are ran:

```
[2020-08-18 03:05:16.298 -05:00] [ERR] [30] Trakt.ScheduledTasks.SyncFromTraktTask: Exception handled
MediaBrowser.Model.Net.HttpException: Service Unavailable
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.Get(HttpRequestOptions options)
   at Trakt.Api.TraktApi.<>c__DisplayClass30_0.<<GetFromTrakt>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Trakt.Api.TraktApi.Retry[T](Func`1 function)
   at Trakt.Api.TraktApi.GetFromTrakt(String url, CancellationToken cancellationToken, TraktUser traktUser)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncFromTraktTask.SyncTraktDataForUser(User user, Double currentProgress, CancellationToken cancellationToken, IProgress`1 progress, Double percentPerUser)
[2020-08-18 03:05:16.307 -05:00] [ERR] [30] Trakt.ScheduledTasks.SyncFromTraktTask: Error syncing trakt data for user "USERA"
MediaBrowser.Model.Net.HttpException: Service Unavailable
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.Get(HttpRequestOptions options)
   at Trakt.Api.TraktApi.<>c__DisplayClass30_0.<<GetFromTrakt>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Trakt.Api.TraktApi.Retry[T](Func`1 function)
   at Trakt.Api.TraktApi.GetFromTrakt(String url, CancellationToken cancellationToken, TraktUser traktUser)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncFromTraktTask.SyncTraktDataForUser(User user, Double currentProgress, CancellationToken cancellationToken, IProgress`1 progress, Double percentPerUser)
   at Trakt.ScheduledTasks.SyncFromTraktTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)

```

I'm using Trakt plugin 10.0.0 and Jellyfin 10.6.2 stable.

**Comment by crobibero** [comment]
Service Unavailable means Trakt is down, nothing we can do to fix that.

**Comment by oddstr13** [comment]
Only thing we could do is to better handle Trakt being unavailable.
