### ISSUE TITLE
plugin work half way on v10.7

### ISSUE THREAD

**Issue by elvis0288** [jellyfin/jellyfin-plugin-trakt#64]
if i set the episode or movie to watched it works but if i just watched it normally and jellyfin set it to watched it is not working.. looking at the logs this is what i get
`
[2021-02-06 11:18:17.785 +00:00] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Sync library to trakt.tv"
[2021-02-06 11:18:18.793 +00:00] [INF] [13] Trakt.ScheduledTasks.SyncLibraryTask: Movies to add to Collection: 0
[2021-02-06 11:18:18.795 +00:00] [INF] [13] Trakt.ScheduledTasks.SyncLibraryTask: Movies to set watched: 0
[2021-02-06 11:18:18.795 +00:00] [INF] [13] Trakt.ScheduledTasks.SyncLibraryTask: Movies to set unwatched: 0
[2021-02-06 11:18:19.777 +00:00] [INF] [13] Trakt.ScheduledTasks.SyncLibraryTask: Episodes to add to Collection: 10
[2021-02-06 11:18:20.086 +00:00] [ERR] [13] Trakt.ScheduledTasks.SyncLibraryTask: TraktResponse not Found: "{}"
[2021-02-06 11:18:20.088 +00:00] [ERR] [13] Trakt.ScheduledTasks.SyncLibraryTask: TraktResponse not Found: "{}"
[2021-02-06 11:18:20.089 +00:00] [ERR] [13] Trakt.ScheduledTasks.SyncLibraryTask: TraktResponse not Found: "{}"
[2021-02-06 11:18:20.091 +00:00] [INF] [13] Trakt.ScheduledTasks.SyncLibraryTask: Episodes to set watched: 4
[2021-02-06 11:18:20.234 +00:00] [ERR] [13] Trakt.ScheduledTasks.SyncLibraryTask: Error updating episode play states
System.Runtime.Serialization.SerializationException: Type definitions should start with a '{', expecting serialized type 'TraktSyncResponse', got string starting with: AUTHED_API_POST_LIMIT rate limit exceeded. Please 
   at ServiceStack.Text.Common.DeserializeTypeRefJson.StringToType(ReadOnlySpan`1 strType, TypeConfig typeConfig, EmptyCtorDelegate ctorFn, KeyValuePair`2[] typeAccessors) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Common\DeserializeTypeRefJson.cs:line 172
   at ServiceStack.Text.Json.JsonReader.<>c__DisplayClass3_0.<GetParseSpanFn>b__0(ReadOnlySpan`1 v) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Json\JsonReader.Generic.cs:line 20
   at ServiceStack.Text.JsonSerializer.DeserializeFromSpan(Type type, ReadOnlySpan`1 value) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\JsonSerializer.cs:line 62
   at ServiceStack.Memory.NetCoreMemory.Deserialize(MemoryStream memoryStream, Boolean fromPool, Type type, DeserializeStringSpanDelegate deserializer) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\NetCoreMemory.cs:line 179
   at ServiceStack.Memory.NetCoreMemory.Deserialize(Stream stream, Type type, DeserializeStringSpanDelegate deserializer) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\NetCoreMemory.cs:line 151
   at ServiceStack.Text.JsonSerializer.DeserializeFromStream[T](Stream stream) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\JsonSerializer.cs:line 190
   at Emby.Server.Implementations.Serialization.JsonSerializer.DeserializeFromStream[T](Stream stream)
   at Trakt.Api.TraktApi.SendEpisodePlaystateUpdatesInternalAsync(IEnumerable`1 episodeChunk, TraktUser traktUser, Boolean seen, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendEpisodePlaystateUpdates(List`1 episodes, TraktUser traktUser, Boolean seen, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.SendEpisodePlaystateUpdates(Boolean seen, TraktUser traktUser, List`1 playedEpisodes, ISplittableProgress`1 progress, CancellationToken cancellationToken)
[2021-02-06 11:18:20.258 +00:00] [INF] [13] Trakt.ScheduledTasks.SyncLibraryTask: Episodes to set unwatched: 0
[2021-02-06 11:18:20.259 +00:00] [INF] [13] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Sync library to trakt.tv" Completed after 0 minute(s) and 2 seconds
[2021-02-06 11:18:20.264 +00:00] [INF] [13] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2021-02-06 11:18:52.481 +00:00] [INF] [20] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2021-02-06 11:19:04.500 +00:00] [INF] [15] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
[2021-02-06 11:19:11.191 +00:00] [INF] [27] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" closed
[2021-02-06 11:20:09.351 +00:00] [INF] [33] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" request`

**Comment by EVOTk** [comment]
On my installation, the plugin does not want to work at all! Which version are you using?

**Comment by EVOTk** [comment]
With the latest unstable version (11.2102.2810.1328) [https://sfo1.mirror.jellyfin.org/releases/plugin/manifest-unstable.json], fully functional on jellyfin 10.7.0!
Big Thx!

**Comment by richierichman** [comment]
Hi can you tell me how you installed the latest unstable version of the plugin. When I add the unstable Repo it installs updates to all the plugins but they all error out with Malfunction and the disabled. I'm having issues syncing my shows from Trakt to Jellyfin. Trying to move my Emby watched state to Jellyfin via Trakt. Thanks in advance.

**Comment by elvis0288** [comment]
Do not use the unstable version I tried that and I had the same issues as you have.. With the v10.7.1 you can use the stable version.. It is working fine for me now
