### ISSUE TITLE
Sync to Trakt fails after 1000~ episodes.

### ISSUE THREAD

**Issue by Remnence** [jellyfin/jellyfin-plugin-trakt#69]
[2021-03-25 13:12:32.026 +00:00] [INF] Episodes to set watched: 0
[2021-03-25 13:12:32.026 +00:00] [INF] Episodes to set unwatched: 0
[2021-03-25 13:12:32.026 +00:00] [INF] "Sync library to trakt.tv" Completed after 1 minute(s) and 56 seconds
[2021-03-25 13:12:32.026 +00:00] [INF] ExecuteQueuedTasks
[2021-03-25 13:27:37.370 +00:00] [INF] Executing "Sync library to trakt.tv"
[2021-03-25 13:27:39.203 +00:00] [INF] Movies to add to Collection: 3
[2021-03-25 13:27:39.512 +00:00] [INF] Movies to set watched: 0
[2021-03-25 13:27:39.513 +00:00] [INF] Movies to set unwatched: 0
[2021-03-25 13:27:53.098 +00:00] [INF] WS "10.10.1.104" closed
[2021-03-25 13:28:28.764 +00:00] [INF] Episodes to add to Collection: 16407
[2021-03-25 13:28:29.230 +00:00] [ERR] Exception handled sending episodes to trakt.tv
System.Runtime.Serialization.SerializationException: Type definitions should start with a '{', expecting serialized type 'TraktSyncResponse', got string starting with: AUTHED_API_POST_LIMIT rate limit exceeded. Please 
   at ServiceStack.Text.Common.DeserializeTypeRefJson.StringToType(ReadOnlySpan`1 strType, TypeConfig typeConfig, EmptyCtorDelegate ctorFn, KeyValuePair`2[] typeAccessors) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Common\DeserializeTypeRefJson.cs:line 172
   at ServiceStack.Text.JsonSerializer.DeserializeFromSpan(Type type, ReadOnlySpan`1 value) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\JsonSerializer.cs:line 62
   at ServiceStack.Memory.NetCoreMemory.Deserialize(MemoryStream memoryStream, Boolean fromPool, Type type, DeserializeStringSpanDelegate deserializer) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\NetCoreMemory.cs:line 189
   at ServiceStack.Text.JsonSerializer.DeserializeFromStream[T](Stream stream) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\JsonSerializer.cs:line 190
   at Trakt.Api.TraktApi.SendLibraryUpdateInternalAsync(IEnumerable`1 episodes, TraktUser traktUser, CancellationToken cancellationToken, EventType eventType)
   at Trakt.Api.TraktApi.SendLibraryUpdateAsync(IReadOnlyList`1 episodes, TraktUser traktUser, CancellationToken cancellationToken, EventType eventType)
   at Trakt.ScheduledTasks.SyncLibraryTask.SendEpisodeCollectionUpdates(Boolean collected, TraktUser traktUser, List`1 collectedEpisodes, ISplittableProgress`1 progress, CancellationToken cancellationToken)

**Comment by Remnence** [comment]
[https://trakt.docs.apiary.io/#introduction/rate-limiting](url)

**Comment by dgalli1** [comment]
Should be fixed on master: https://github.com/jellyfin/jellyfin-plugin-trakt/pull/65
