### ISSUE TITLE
Syncing collection not working (10.7.5)

### ISSUE THREAD

**Issue by herrwusel** [jellyfin/jellyfin-plugin-trakt#79]
While scrobbling is working the plugin fails to synchronize the collection to trakt:
```
[2021-05-23 17:23:45.510 +02:00] [ERR] Tried to reauthenticate with Trakt, but no refreshToken was available
[2021-05-23 17:23:45.670 +02:00] [ERR] Tried to reauthenticate with Trakt, but no refreshToken was available
[2021-05-23 17:23:45.844 +02:00] [ERR] Error
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Trakt.ScheduledTasks.SyncFromTraktTask.FindMatch(BaseItem item, IEnumerable`1 results)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncUserLibrary(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2021-05-23 17:23:45.844 +02:00] [INF] "Sync library to trakt.tv" Failed after 0 minute(s) and 0 seconds
```

**Comment by Guido83** [comment]
Same issue here. I am running  10.7.6 with trakt plugin 12.0.0

**Comment by Guido83** [comment]
Actually I am geeting this Error Log (tried reinstalling the plugin and forcing re-authentification). The Import of Play states is working though;
`[2021-07-08 07:45:32.429 +00:00] [INF] [40] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Sync library to trakt.tv"
[2021-07-08 07:45:32.429 +00:00] [ERR] [40] Trakt.Api.TraktApi: Tried to reauthenticate with Trakt, but no refreshToken was available
[2021-07-08 07:45:32.842 +00:00] [ERR] [36] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncUserLibrary(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2021-07-08 07:45:32.845 +00:00] [INF] [36] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Sync library to trakt.tv" Failed after 0 minute(s) and 0 seconds`

**Comment by Guido83** [comment]
I got it working now. Deleted the plugin first and the most important part:
I deleted the Trakt.xml from Jellyfin/config/plugins/configurations. This file contained some elder information which caused the sync fail.
After all I re-installed the trakt plugin, configured it and it is working now.

**Comment by Shadowghost** [comment]
Requires a manual re-auth via the UI (since there was no refresh token available to extend the current token). We can't do much in this case.
