### ISSUE TITLE
Trakt error seems to stop episode playback.

### ISSUE THREAD

**Issue by alexandrucatalinene** [jellyfin/jellyfin-plugin-trakt#81]
Trakt is making playback stop. When it fails the episode fails to load and I just get the background of the movie (probabil the frame extracted by jellyfin). This is on the tizen app.

```
[ERR] Exception handled sending status update
System.Runtime.Serialization.SerializationException: Type definitions should start with a '{', expecting serialized type 'TraktScrobbleResponse', got string starting with: AUTHED_API_POST_LIMIT rate limit exceeded. Please
at ServiceStack.Text.Common.DeserializeTypeRefJson.StringToType(ReadOnlySpan`1 strType, TypeConfig typeConfig, EmptyCtorDelegate ctorFn, KeyValuePair`2[] typeAccessors) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\Common\DeserializeTypeRefJson.cs:line 172
at ServiceStack.Text.JsonSerializer.DeserializeFromSpan(Type type, ReadOnlySpan`1 value) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\JsonSerializer.cs:line 62
at ServiceStack.Memory.NetCoreMemory.Deserialize(MemoryStream memoryStream, Boolean fromPool, Type type, DeserializeStringSpanDelegate deserializer) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\NetCoreMemory.cs:line 189
at ServiceStack.Text.JsonSerializer.DeserializeFromStream[T](Stream stream) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\JsonSerializer.cs:line 190
at Trakt.Api.TraktApi.SendEpisodeStatusUpdateAsync(Episode episode, MediaStatus status, TraktUser traktUser, Single progressPercent)
at Trakt.ServerMediator.KernelPlaybackStart(Object sender, PlaybackProgressEventArgs e)
```

Version: 11.0.0
Jellyfin version: 10.7.5 x64 on Linux

**Comment by Shadowghost** [comment]
Should have been fixed by #65
