### ISSUE TITLE
Trakt Refuses To Sync: The Input Doesn't Contain Any JSON Tokens

### ISSUE THREAD

**Issue by brando56894** [jellyfin/jellyfin-plugin-trakt#99]
I've had this issue for over a year now and finally decided to report it since Trkat works for other users. On a fresh install of Jellyfin, (version doesn't matter, but currently running v10.7.7 on Arch Linux), after importing my library and setting up Trakt, it refuses to pull down watched states or sync my library. I saw one report mention that this may be due to filesystem permissions but I ran Jellyfin as root just to be sure, and it gives the same issue.

The stack trace is as follows
```
System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncFromTraktTask.SyncTraktDataForUser(User user, Double currentProgress, CancellationToken cancellationToken, IProgress`1 progress, Double percentPerUser)
[2022-01-10 12:41:23.897 -05:00] [ERR] [25] Trakt.ScheduledTasks.SyncFromTraktTask: Error syncing trakt data for user "bran"
```

**Comment by haykkh** [comment]
Hello, have you tried [this](https://github.com/jellyfin/jellyfin-plugin-trakt/issues/79#issuecomment-881267918)? 
> I got it working now. Deleted the plugin first and the most important part: I deleted the Trakt.xml from Jellyfin/config/plugins/configurations. This file contained some elder information which caused the sync fail. After all I re-installed the trakt plugin, configured it and it is working now.


Seems to be a temporary fix until something more permanent is figured out.

**Comment by NHellFire** [comment]
Seeing this as well, same exception. Deleting the config file and setting up again doesn't help.

**Comment by fdw** [comment]
This worked for me. It seems that the new config file contains access and refresh tokens, which the previous one didn't.

**Comment by jasondaigo** [comment]
i deleted the config file and it keeps failing even faster now. so also not helping on my side. jf 10.7.7, trakt 12.
it worked fine since yesterday i believe; something changed. reforced auth and reauth 2 times too now.
```
[2022-04-12 11:19:20.905 +02:00] [INF] Executing "Sync library to trakt.tv"
[2022-04-12 11:19:20.999 +02:00] [ERR] Tried to reauthenticate with Trakt, but no refreshToken was available
[2022-04-12 11:19:21.914 +02:00] [INF] Sending ForceKeepAlive message to 1 inactive WebSockets.
[2022-04-12 11:19:21.914 +02:00] [INF] Lost 1 WebSockets.
[2022-04-12 11:19:21.925 +02:00] [ERR] Error
System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Trakt.Api.TraktApi.SendGetAllWatchedMoviesRequest(TraktUser traktUser)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncMovies(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.SyncUserLibrary(User user, TraktUser traktUser, ISplittableProgress`1 progress, CancellationToken cancellationToken)
   at Trakt.ScheduledTasks.SyncLibraryTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2022-04-12 11:19:21.951 +02:00] [INF] "Sync library to trakt.tv" Failed after 0 minute(s) and 1 seconds
```

**Comment by jasondaigo** [comment]
was probably said already somewhere, but deleting that file while the server is running didnt help. while first stopping it, then deleting the file and restart jellyfin seems to work? :-)

**Comment by Shadowghost** [comment]
Config files are only recreated when Jellyfin restarts. AFAIK if it's delete while Jellyfin is still running it might just rewrite the current bad config from memory when something triggers a save.

**Comment by Shadowghost** [comment]
Should be fixed by https://github.com/jellyfin/jellyfin-plugin-trakt/pull/115
